export const PRODUCT_FILES = {
  1:  { name: 'Proveedor de Legos',                    files: ['alamcen/lego-contacto.jpg'] },
  2:  { name: 'Proveedor de Relojes',                  files: ['alamcen/relojes-contacto.jpg.jpg'] },
  3:  { name: 'Proveedor de Perfumes',                 files: ['alamcen/perfumes-contacto.jpg'] },
  4:  { name: 'Proveedor Tecnologia',                  files: ['alamcen/tecnologia-contacto.jpg'] },
  5:  { name: 'Proveedor de Ropa',                     files: ['alamcen/ropa+zapas-contacto.jpg'] },
  6:  { name: 'Proveedor de Zapatos',                  files: ['alamcen/ropa+zapas-contacto.jpg'] },
  7:  { name: 'Pack Ropa y Zapatos',                   files: ['alamcen/ropa+zapas-contacto.jpg'] },
  8:  { name: 'Proveedor Vaperes',                     files: ['alamcen/vaperes-contactos.jpg'] },
  9:  { name: 'Pack Accesorios y Ropa',                files: ['alamcen/accesorios+ropa-contacto.jpg'] },
  10: { name: 'Pulseras LV',                           files: ['alamcen/pulserasLV-contacto.jpg'] },
  11: { name: 'Lafufus',                               files: ['alamcen/lafufus-contacto.jpg'] },
  12: { name: 'Pack +99 Facturas y Tickets Editables', files: ['TICKET Y FACTURAS.zip'] },
  13: { name: 'Guía Avanzada de Ventas y Neuroventa',  files: ['alamcen/Guia_Avanzada_Ventas.pdf'] },
  14: { name: 'Guía Maestra de Reventa y Arbitraje',   files: ['alamcen/Guia_Maestra_Reventa.pdf'] },
  15: { name: 'Manual Definitivo de Dropshipping y Ecommerce', files: ['alamcen/Guia_Definitiva_Dropshipping.pdf'] },
  16: { name: 'Shopify, Dropshipping & E-Commerce Maestro',    files: ['alamcen/Manual_Maestro_Shopify_Dropshipping_2026.pdf'] },
  17: { name: 'Pack Guías Completo', files: [
    'alamcen/Guia_Avanzada_Ventas.pdf',
    'alamcen/Guia_Maestra_Reventa.pdf',
    'alamcen/Guia_Definitiva_Dropshipping.pdf',
    'alamcen/Manual_Maestro_Shopify_Dropshipping_2026.pdf',
    'alamcen/Guion Carreras Legales.pdf',
  ]},
};
